### ISSUE TITLE
Issue getting it to work

### ISSUE THREAD

**Issue by KCS-Mack** [ztepler/quipuswap-tezos-analysis-colab#1]
<img width="1205" alt="Screen Shot 2021-04-27 at 9 33 29" src="https://user-images.githubusercontent.com/20471099/116167695-b2d2ca80-a73b-11eb-9d8c-75702e4bd8cd.png">

Sorry a newbie at this, I opened with Jupiter notebook, what do I do now?

**Comment by ztepler** [comment]
You can run this cells using [▶Run] button on top. It is required to install pandas, matplotlib and seaborn using conda or pip, if it is not installed already in your environment.

The easiest way to run this code is to use Google Colab link provided in README.md:
https://colab.research.google.com/github/ztepler/quipuswap-tezos-analysis-colab/blob/main/QuipuSwap_Tezos_Pool_Analysis.ipynb

Google Colab already have all required dependencies installed.
